tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      python manage.py migrate
  - command: |
      source venv/bin/activate
      python manage.py runserver
ports:
  - port: 8000
    onOpen: open-browser
vscode:
  extensions:
    - ms-azuretools.vscode-docker
